### ISSUE TITLE
missing bigint in 4.00.00

### ISSUE THREAD

**Issue by jarro2783** [fbb-git/bobcat#1]
I can't compile 4.00.00.

After cloning the repository I did the following:

```
git checkout 4.00.00
```

I edited INSTALL.md to use c++11, then did

```
./build libraries
```

I followed the prompts and built readline but not the others. Then I get the following error:

```
In file included from primefactors/primefactors.ih:1:0,
             from primefactors/reduce.cc:1:
primefactors/primefactors:9:25: fatal error: bobcat/bigint: No such file or directory
 #include <bobcat/bigint>
```

**Comment by fbb-git** [comment]
Dear jarro2783, you wrote:

> I can't compile 4.00.00.
> 
> After cloning the repository I did the following:
> 
> ```
> git checkout 4.00.00
> ```
> 
> I edited INSTALL.md to use c++11, then did

Thanks for you e-mail about bobcat. There is an obvious reason for the problem
you mention. But first some minor notes:

```
I assume you refer to INSTALL.im, and not INSTALL.md? Afaik there is no
```

INSTALL.ml in bobcat's distribution.

```
I wonder why you changed c++14 to c++11: to me it suggests that you're
```

using an older compiler. You might consider upgrading, although your problem
has nothing to do with using c++11.

> ```
> ./build libraries
> ```
> 
> I followed the prompts and built readline but not the others. 

That's causing the problem: Bigint depends on the SSL library, that's why it's
mentioned in the file SSLCLASSES. As long as you leave out that dependency you
won't get the BigInt class, I'm afraid.

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by fbb-git** [comment]
On second thought: it still isn't OK, and you're rightly complaining, since PrimeFactors depends on BigInt and should therefore be in SSLCLASSES, and not in CLASSES. So that's an error, which I'll fix asap.

Apologies for my first reaction.

**Comment by fbb-git** [comment]
I just pushed a fix (commit 61c5aa707a6474e89a9081973756035f63e2bf2c) for jarro2783's issue with compiling Bobcat without dependencies on other non-standard libraries. Btw, if you know you don't want these dependencies, then 'build light' now directly builds Bobcat without these dependencies, with no questions asked.

I'm closing this issue now.

**Comment by jarro2783** [comment]
Thanks. Yes I meant INSTALL.im, I think I had markdown on my mind at the time. My distro has gcc 4.8 which only has c++11, so I changed it to that hoping that it would work, it does seem to work. I built with ssl and it works fine.

**Comment by fbb-git** [comment]
Dear jarro2783, you wrote:

> Thanks. Yes I meant INSTALL.im, I think I had markdown on my mind at the
> time. My distro has gcc 4.8 which only has c++11, so I changed it to that
> hoping that it would work, it does seem to work. I built with ssl and it works
> fine.

Hi Jarro,

C+++11 is fine, don't worry, there's nothing specific c++14 yet in
Bobcat. Nice to read that all's well. Thanks for the feedback.

Cheers,

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```
