### ISSUE TITLE
signal/signal.cc:29:33: error: 'sighandler_t' has not been declared

### ISSUE THREAD

**Issue by poetaster** [fbb-git/bobcat#8]
Up front, compiling on freebsd. Having applied patches and FLAGS as per INSTALL.nn.

everything compiles until:

```
Compiling signal
g++ --std=c++14 -O2 -Wall -fdiagnostics-color=never -D_GLIBCXX_USE_C99 -isystem tmp -c -o signal/oa/88signal.o signal/signal.cc
signal/signal.cc:29:33: error: 'sighandler_t' has not been declared
 void Signal::signal(int signum, sighandler_t handler)
                                 ^~~~~~~~~~~~
signal/signal.cc: In member function 'void FBB::Signal::signal(int, int)':
signal/signal.cc:33:21: error: invalid conversion from 'int' to 'void (*)(int)' [-fpermissive]
     sa.sa_handler = handler;
                     ^~~~~~~
Fatal: system - failure of system call (status 256)


```

Must also note that I have c  experience but not c++ :<

**Comment by poetaster** [comment]
INSTALL.im:
#define CXXFLAGS    "--std=c++14 -O2 -Wall -fdiagnostics-color=never -D_GLIBCXX_USE_C99"
#define LDFLAGS    "-dynamiclib -Wl,-single_module

**Comment by fbb-git** [comment]
Dear Mark Washeim, you wrote:
> Up front, compiling on freebsd. Having applied patches and FLAGS as per INSTALL.nn.
> 
> everything compiles until:
> 
> ```
> Compiling signal
> g++ --std=c++14 -O2 -Wall -fdiagnostics-color=never -D_GLIBCXX_USE_C99 -isystem tmp -c -o signal/oa/88signal.o signal/signal.cc
> signal/signal.cc:29:33: error: 'sighandler_t' has not been declared
>  void Signal::signal(int signum, sighandler_t handler)
>                                  ^~~~~~~~~~~~
> signal/signal.cc: In member function 'void FBB::Signal::signal(int, int)':
> signal/signal.cc:33:21: error: invalid conversion from 'int' to 'void (*)(int)' [-fpermissive]
>      sa.sa_handler = handler;
>                      ^~~~~~~
> Fatal: system - failure of system call (status 256)

Hm.... First of all: thanks for your report. Let's see what happens:

  * std c++14 is by now kind of old. I suggest you change that into c++17
    The next bobcat release probably uses that std anyway.

  * -DGLIBCXX_USE_C99 probably is something that's required by freebsd? I
    don't use freebsd, so I can't check this out.

  * In the signal(2) manpage I find

       typedef void (*sighandler_t)(int);

    In that same man-page I read

       The use of sighandler_t is a GNU extension, exposed if  _GNU_SOURCE  is
       defined;  glibc  also  defines  (the  BSD-derived) sig_t if _BSD_SOURCE
       (glibc 2.19 and earlier) or _DEFAULT_SOURCE (glibc 2.19 and  later)  is
       defined. 

    Apparently _GNU_SOURCE is defined when using Linux. Maybe your problem
    disappears after including the sighandler_t definition. Alternatively, you
    could try to add -D_GNU_SOURCE to the set of compiler options.

Hopefully my suggestions help you to solve your problem.

Cheers,

-- 
    Frank B. Brokken
    Center for Information Technology, University of Groningen
    (+31) 50 363 9281 
    Public PGP key: http://pgp.surfnet.nl
    Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA

**Comment by poetaster** [comment]
Ah that clarifies it :) thanks. I'm split 60/40 linux/bsd:

the FreeBSD (10.x) manpage (SIGNAL(3)) has:

```
SYNOPSIS
     #include <signal.h>

     void
     (*signal(int sig, void (*func)(int)))(int);

     or in FreeBSD's equivalent but easier to read typedef'd version:

     typedef void (*sig_t) (int);

     sig_t
     signal(int sig, sig_t func);

```
-D_GNU_SOURCE  did not do the trick but does yield more information :)

Thanks you, I'll follow up as soon as I find a clean solution.

**Comment by fbb-git** [comment]
Dear Mark Washeim, you wrote:

> Ah that clarifies it :) thanks. I'm split 60/40 linux/bsd:

And thank you for your reply.

Cheers,

-- 
    Frank B. Brokken
    Center for Information Technology, University of Groningen
    (+31) 50 363 9281 
    Public PGP key: http://pgp.surfnet.nl
    Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA

**Comment by poetaster** [comment]
Hmmm. Turned out, compiling with g++ or clang with --std=c++17 that:
I needed to edit sighandler_t and write: __sighandler_t

Could be done with the freebsd patch you include.

There are some other issues, but I'll put those in another context. And I see you're moving to gitlab.
