### ISSUE TITLE
gethostent/solvename.cc: variable 'sockaddr_in addr' has initializer but incomplete type

### ISSUE THREAD

**Issue by poetaster** [fbb-git/bobcat#9]
g++ --std=c++17 -O2 -Wall -fdiagnostics-color=never -isystem tmp -c -o gethostent/oa/26solvename.o gethostent/solvename.cc

gethostent/solvename.cc: In static member function 'static void FBB::GetHostent::solveName(const char*, const string&)':

gethostent/solvename.cc:13:24: error: variable 'sockaddr_in addr' has initializer but incomplete type
     struct sockaddr_in addr{AF_INET};

**Comment by fbb-git** [comment]
Dear Mark Washeim, you wrote:
> gethostent/solvename.cc: In static member function 'static void FBB::GetHostent::solveName(const char*, const string&)':
> gethostent/solvename.cc:13:24: error: variable 'sockaddr_in addr' has initializer but incomplete type
>      struct sockaddr_in addr{AF_INET};

Hi Mark,

Thx for your report. Please use the version at gitlab, as github is no longer
maintained. If you still experience your problem with the gitlab version, then
please let me know. A small example of a program in which you encountered the
problem would also be very helpful. Bobcat's current location is

    https://fbb-git.gitlab.io/bobcat/

Cheers,

-- 
    Frank B. Brokken
    Center for Information Technology, University of Groningen
    (+31) 50 363 9281 
    Public PGP key: http://pgp.surfnet.nl
    Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
